// JavaScript Document
function dw(key) {document.write(key);}
//--------------------------------------
var K1 = "2JF8yrgsM5H261Gju4rzKfxFurDZluOfWUq9UnCV";
var K2 = "xlirVc4ZbYnah6b97WEo4mbOUBvi0RiqZj5GJ9Hi";
var K3 = "pintUUOFdx";
var K4 = "Gi5mwesLdM";
var K5 = "NzNsbc63DG";
var GMTTIME = "+08:00";

var AL_empty = " can not be empty!";
var BT_add = "Add";
var BT_addauthor = "Add Author";
var BT_search = "Check";
var BT_upload = "Upload";
var ERR_queryfail = "Query failed";
var STR_1 = "* is required";
var STR_address = "Address";
var STR_author = "Author";
var STR_capacity = "Capacity";
var STR_careercontent = "Content";
var STR_careerinstitution = "Institution";
var STR_contactname = "Contact Person";
var STR_contactemail = "Contact Email";
var STR_content = "Content";
var STR_coordinates = "Coordinates";
var STR_date = "Date";
var STR_description = "Description";
var STR_email = "Email";
var STR_end = "End";
var STR_event = "Event";
var STR_firstname = "First Name";
var STR_hiring = "Post Type";
var STR_institution = "Institution";
var STR_jobname = "Name";
var STR_lastname = "Last Name";
var STR_location = "Location";
var STR_note = "Note";
var STR_pdffile = "PDF File";
var STR_phone = "Phone";
var STR_photo = "Photo";
var STR_name = "Name"
var STR_position = "Position";
var STR_postedby = "Posted by";
var STR_searchexist = "Already exists? ";
var STR_session = "Session";
var STR_start = "Start";
var STR_time = "Time";
var STR_timeend = "End Time";
var STR_timestart = "Start Time";
var STR_title = "Title";
var STR_username = "User Name";
var STR_webpage = "Web Page";
var STR_website = "Website";
var TT_list = "List";
var TT_main = "Data Upload";
var TT_menu = "Menu";
var TT_top = "Top";
var TT_addabstract = "Add Abstract";
var TT_addannounce = "Add Announcement";
var TT_addcareer = "Add Career";
var TT_addevent = "Add Event";
var TT_addlocation = "Add Location";
var TT_addperson = "Add Person";
var TT_addposter = "Add Poster";
var TT_addsession = "Add Session";
var TT_addtalk = "Add Talk";
var TT_addvenue = "Add Venue";
var TT_instructions = "Instructions";
var TT_listannounce = "Annoucement List";
var TT_listcareer = "Career List";
var TT_listevent = "Event List";
var TT_listlocation = "Location List";
var TT_listperson = "Person List";
var TT_listsession = "Session List";
var TT_listtalk = "Talk List";
var TT_listvenue = "Venue List";
var TT_toptitle = "Colloquium.me Data Uploader beta";

var STR_event_name = "Event Name";
var STR_event_description = "Event Description";
var STR_event_startdate = "Start Date";
var STR_event_enddate = "End Date";
var STR_event_organizer = "Organizer (institute or person)";

var STR_event_multiple = "Events (hold shift or ctrl to select multiple)";

var OPT_career_available = "Position Available";
var OPT_career_seeking = "Seeking Job";

var OPT_persontitle_professor = "Professor";
var OPT_persontitle_postdoc = "Postdoc";
var OPT_persontitle_doctor = "PhD Student";
var OPT_persontitle_master = "Master Student";
var OPT_persontitle_bachelor = "Bachelorr Student";
var OPT_persontitle_other = "other";

var STR_2 = "Add events first, then persons, finally talks. we can skip the venue part and all secondary data for now";
var STR_3 =	"Go to https://www.parse.com/apps/cm_math_one/collections to view the data ";
var STR_4 = "(You will need a free account from Parse.com)";